import type { Metadata } from 'next'

import SessionProvider from '@/components/SessionProvider'
import ThemeProvider from '@/components/ThemeProvider'
import { Toaster } from '@/components/ui/toaster'
import { Inter } from 'next/font/google'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Welcome to Tasklist!',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body className={inter.className}>
          <SessionProvider>
            <main>{children}</main>
          </SessionProvider>
          <Toaster />
        </body>
      </ThemeProvider>
    </html>
  )
}
