import { Metadata } from 'next'

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: "Welcome! What's new?",
}

export default function Page() {
  return <div>dashboard</div>
}
